<?php

$lang_pmsn = array(

'PM'		=> 'YV',
'list'		=> 'Keskusteluni',
'listq'		=> 'Processing of dialogues',
'new'		=> 'Uudet viestit',
'newq'		=> 'Processing of dialogues',
'close'		=> 'YV pois päältä',
'closeq'	=> 'Varmista YV estäminen',
'save'		=> 'Viestien arkistointi',
'saveq'		=> 'Poista keskustelut',
'post'		=> 'Uusi viesti',
'blocking'	=> 'Estä lähettäjä',
'blocked'	=> 'Estetyt käyttäjät',
'blockedq'	=> 'Estojen poisto',
'topic'		=> 'Keskustelu',
'del'		=> 'Poista',
'send'		=> 'Lähetä',
'edit'		=> 'Muokkaa viestiä',

'mNew'		=> 'Uusi',
'mList'		=> 'Keskustelut',
'mSave'		=> 'Arkistoi',

'Off' => 'Estä YV:t',
'On' => 'Salli YV:t',
'Email on' => 'Ilmoita sähköpostilla',
'Email off' => 'Älä ilmoita sähköpostilla',
'Email on Red' => 'Sähköpostilla ilmoittaminen päällä. Uudelleenohjataan…',
'Email off Red' => 'Sähköpostilla ilmoittaminen on pois päältä. Uudelleenohjataan…',

'Boxs' => 'Kansiot',
'Storage' => 'Tila',
'Options' => 'Asetukset',

'tDialog' => 'Keskustelun aihe',
'tStarter' => 'Aloittaja',
'tTo' => 'Vastaanottaja',
'tReplies' => 'Vastaukset',
'tLast' => 'Viimeinen',

'Info zero' => 'Ei keskusteluja tässä kansiossa.',
'Post new topic' => 'Aloita uusi keskustelu',
'New dialog' => 'Uusi keskustelu',
'Addressee' => 'Vastaanottaja',
'Dialog head' => 'Keskustelun aihe',
'Save_' => 'Arkistoi',
'Save_Later' => 'Arkistoi (Lähetä myöhemmin)',
'Delete' => 'Poista',
'Add Reply' => 'Lisää vastaus',
'Block' => 'Estä',
'Send d' => 'Lähetä keskustelu',

'Deleted' => 'Poistettu:',
'Yes' => ' Kyllä ',
'With' => ' kanssa ',

'No subject' => 'Aiheilla tulee olla otsikko.',
'Too long message' => 'Viestit eivät voi olla pidempiä kuin 65535 merkkiä.',
'No addressee' => 'Annetulla käyttäjätunnuksella ei löytynyt käyttäjiä.',
'No for itself' => 'Et voi lähettää yksityisviestiä itsellesi.',
'Off messages' => 'Tämä käyttäjä on estänyt yksityisviestien käytön.',
'More maximum' => 'Käyttäjän kansiot ovat täynnä.',
'More maximum user' => 'Arkistokansio on täynnä.',
'More maximum list' => 'Keskustelukansiot ovat täynnä.',
'Empty' => 'Tyhjä.',
'No dialogs' => 'Et ole valinnut yhtään keskustelua käsiteltäväksi.',
'Err1' => 'Dialogues not belonging to you have been selected.',
'Err2' => 'It is not possible to have that many dialogues.',
'No block itself' => 'Et voi estää itseäsi.',
'No block admin' => 'Et voi estää ylläpitäjää.',
'Full folders' => 'Kansiosi ovat täynnä.',
'No new post' => 'Tähän keskusteluun ei voi lisätä uusia viestejä.',
'You block addr' => 'Viestin lähettäminen ei onnistu, koska olet estänyt käyttäjän.',
'Addr block you' => 'Viestin lähettäminen ei onnistu, koska käyttäjä on estänyt sinut.',
'No edit post' => 'Käyttäjä on jo lukenut viestin.',

'Info' => 'Tietoja',
'Info close' => 'Olet estänyt yksityisviestit.',
'InfoQ' => 'Vahvista yksityisviestien estäminen',
'InfoQ close' => 'Varoitus! Yksityisviestien estäminen poistaa kaikki käymäsi yksityisviestit.',
'InfoQS' => 'Esti YV:t',
'Options redirect' => 'Asetukset muutettu. Uudelleenohjataan…',
'List redirect' => 'Keskustelut käsitelty. Uudelleenohjataan…',
'InfoDeleteQ' => 'Vahvista poistaminen',
'InfoSaveQ' => 'Vahvista tallentaminen',
'InfoDeleteQm' => 'Oletko varma, että haluat poistaa valitut keskustelut?',
'InfoSaveQm' => 'Oletko varma, että haluat siirtää valitut keskustelut arkistoon?',
'InfoBlocking' => 'Estä käyttäjä',
'InfoReBlocking' => 'Poista käyttäjän esto',
'InfoReBlockingS' => 'Poista käyttäjiltä esto',
'InfoReBlockingSQ' => 'Oletko varma, että haluat poistaa eston valituilta käyttäjiltä?',
'InfoBlockingm' => 'Oletko varma, että haluat estää käyttäjiä lähettämästä yksityisviestejä sinulle?',
'InfoReBlockingm' => 'Oletko varma, että haluat sallia yksityisviestien vastaanottamisen muilta käyttäjiltä??',
'Blocking redirect' => 'Esto lisätty. Uudelleenohjataan…',
'ReBlocking redirect' => 'Esto poistettu. Uudelleenohjataan…',
'Topic review' => 'Aiheet (uusin ensin)',
'InfoDeleteMes' => 'Oletko varma, että haluat poistaa viestin keskustelusta &rdquo;%s&rdquo;?',
'InfoDeleteTop' => 'Oletko varma, että haluat poistaa tämän &rdquo;%s&rdquo; keskustelun?',
'DelTop redirect' => 'Keskustelu poistettu. Uudelleenohjataan…',
'DelMes redirect' => 'Viesti poistettu. Uudelleenohjataan…',
'InfoDeleteQMes' => 'Vahvista tämän viestin poistaminen',
'InfoDeleteQTop' => 'Vahvista tämän keskustelun poistaminen',
'InfoSend' => 'Lähetetään keskustelua &rdquo;%s&rdquo;',
'InfoSendQ' => 'Lähetä keskustelu käyttäjälle <strong>%s</strong>?',
'Attention' =>  'Huomio!!!',
'Delete dialog' => 'Poista keskustelut sinun ja tämän käyttäjän välillä',

'Modul failed message' => 'Moduulin &rdquo;%s&rdquo; lataaminen epäonnistui.',
'No modul message' => 'Moduulia ei löytynyt nimellä &rdquo;%s&rdquo;.',
'Min post' => 'Sinun tulee kirjoittaa vähintään %s viestiä keskustelualueelle enenkä voit lähettää yksityisviestejä.',
'Warn' => '<b>Huomio!!!</b><br />Et voi saada vastausta käyttäjältä ennenkä hän on kirjoittanut %s viestiä keskustelualueelle.',

);
